<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

defined('MOODLE_INTERNAL') || die();

/**
 * @package     local_shop
 * @category    local
 * @author      Valery Fremaux <valery.fremaux@gmail.com>
 * @copyright   Valery Fremaux <valery.fremaux@gmail.com> (MyLearningFactory.com)
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * @Todo : check use of this file and redraw to standard country listing
 */

$country = array (

'XX' => 'Choisir un pays...',
'AF' => 'Afghanistan',
'ZA' => 'Afrique du Sud',
'AL' => 'Albanie',
'DZ' => 'Algerie',
'DE' => 'Allemagne',
'AD' => 'Andorre',
'AO' => 'Angola',
'AI' => 'Anguilla',
'AQ' => 'Antarctique',
'AG' => 'Antigua-et-barbuda',
'AN' => 'Antilles Neerlandaises',
'SA' => 'Arabie Saoudite',
'AR' => 'Argentine',
'AM' => 'Armenie',
'AW' => 'Aruba',
'AU' => 'Australie',
'AT' => 'Autriche',
'AZ' => 'Azerbaidjan',
'BY' => 'Belarus',
'BJ' => 'Benin',
'BS' => 'Bahamas',
'BH' => 'Bahrein',
'BD' => 'Bangladesh',
'BB' => 'Barbade',
'BE' => 'Belgique',
'BZ' => 'Belize',
'BM' => 'Bermudes',
'BT' => 'Bhoutan',
'BO' => 'Bolivie',
'BA' => 'Bosnie-Herzegovine',
'BW' => 'Botswana',
'BR' => 'Bresil',
'BN' => 'Brunei Darussalam',
'BG' => 'Bulgarie',
'BF' => 'Burkina Faso',
'BI' => 'Burundi',
'CI' => 'Cote Ivoire',
'KH' => 'Cambodge',
'CM' => 'Cameroun',
'CA' => 'Canada',
'CV' => 'Cap-Vert',
'CL' => 'Chili',
'CN' => 'Chine',
'CY' => 'Chypre',
'CO' => 'Colombie',
'KM' => 'Comores',
'CG' => 'Congo',
'CR' => 'Costa Rica',
'HR' => 'Croatie',
'CU' => 'Cuba',
'DK' => 'Danemark',
'DJ' => 'Djibouti',
'DM' => 'Dominique',
'EG' => 'Egypte',
'SV' => 'El Salvador',
'AE' => 'Emirats Arabes Unis',
'EC' => 'Equateur',
'ER' => 'Erythree',
'US' => 'Etats-Unis',
'FM' => 'Etats Federes de Micronesie',
'ET' => 'Ethiopie',
'ES' => 'Espagne',
'EE' => 'Estonie',
'MK' => 'Ex-Republique Yougoslave de Macedoine',
'RU' => 'Federation de Russie',
'FJ' => 'Fidji',
'FI' => 'Finlande',
'FR' => 'France',
'GE' => 'Georgie',
'GS' => 'Georgie du Sud et les Iles Sandwich du Sud',
'GA' => 'Gabon',
'GM' => 'Gambie',
'GH' => 'Ghana',
'GI' => 'Gibraltar',
'GR' => 'Grece',
'GD' => 'Grenade',
'GL' => 'Groenland',
'GP' => 'Guadeloupe',
'GU' => 'Guam',
'GT' => 'Guatemala',
'GG' => 'Guernesey',
'GN' => 'Guinee',
'GW' => 'Guinee-Bissau',
'GQ' => 'Guinee equatoriale',
'GY' => 'Guyana',
'GF' => 'Guyane Francaise',
'HT' => 'Haiti',
'HN' => 'Honduras',
'HK' => 'Hong-kong',
'HU' => 'Hongrie',
'BV' => 'Ile Bouvet',
'CX' => 'Ile Christmas',
'IM' => 'Ile de Man',
'HM' => 'Ile Heard et Iles Mcdonald',
'NF' => 'Ile Norfolk',
'AX' => 'Iles Aland',
'KY' => 'Iles Caimanes',
'CC' => 'Iles Cocos (Keeling)',
'CK' => 'Iles Cook',
'FO' => 'Iles Feroe',
'FK' => 'Iles Falkland (Malvinas)',
'MP' => 'Iles Mariannes du Nord',
'LY' => 'Iles Mariannes du Nord',
'MH' => 'Iles Marshall',
'UM' => 'Iles mineures eloignees des Etats-Unis',
'SB' => 'Iles Salomon',
'TC' => 'Iles Turks et Caiques',
'VG' => 'Iles Vierges Britanniques',
'VI' => 'Iles Vierges des Etats-Unis',
'IN' => 'Inde',
'ID' => 'Indonesie',
'IQ' => 'Iraq',
'IE' => 'Irlande',
'IS' => 'Islande',
'IL' => 'Israel',
'IT' => 'Italie',
'JM' => 'Jamaique',
'JP' => 'Japon',
'JE' => 'Jersey',
'JO' => 'Jordanie',
'KZ' => 'Kazakhstan',
'KE' => 'Kenya',
'KG' => 'Kirghizistan',
'KI' => 'Kiribati',
'KW' => 'Koweit',
'LS' => 'Lesotho',
'LV' => 'Lettonie',
'LR' => 'Liberia',
'LB' => 'Liban',
'LI' => 'Liechtenstein',
'LT' => 'Lituanie',
'LU' => 'Luxembourg',
'MO' => 'Macao',
'MG' => 'Madagascar',
'MY' => 'Malaisie',
'MW' => 'Malawi',
'MV' => 'Maldives',
'ML' => 'Mali',
'MT' => 'Malte',
'MA' => 'Maroc',
'MQ' => 'Martinique',
'MU' => 'Maurice',
'MR' => 'Mauritanie',
'YT' => 'Mayotte',
'MX' => 'Mexique',
'MC' => 'Monaco',
'MN' => 'Mongolie',
'ME' => 'Montenegro',
'MS' => 'Montserrat',
'MZ' => 'Mozambique',
'MM' => 'Myanmar',
'NP' => 'Nepal',
'NA' => 'Namibie',
'NR' => 'Nauru',
'NI' => 'Nicaragua',
'NG' => 'Nigeria',
'NE' => 'Niger',
'NU' => 'Niue',
'NO' => 'Norvege',
'NC' => 'Nouvelle-Caledonie',
'NZ' => 'Nouvelle-Zelande',
'OM' => 'Oman',
'UG' => 'Ouganda',
'UZ' => 'Ouzbekistan',
'PE' => 'Perou',
'PK' => 'Pakistan',
'PW' => 'Palaos',
'PA' => 'Panama',
'PG' => 'Papouasie-Nouvelle-Guinee',
'PY' => 'Paraguay',
'NL' => 'Pays-Bas',
'PH' => 'Philippines',
'PN' => 'Pitcairn',
'PL' => 'Pologne',
'PF' => 'Polynesie Francaise',
'PR' => 'Porto Rico',
'PT' => 'Portugal',
'TW' => 'Province de Chine Taiwan',
'QA' => 'Qatar',
'TZ' => 'Republique-Unie de Tanzanie',
'SY' => 'Republique Arabe Syrienne',
'CF' => 'Republique centrafricaine',
'CD' => 'Republique Democratique du Congo',
'LA' => 'Republique Democratique Populaire Lao',
'KR' => 'Republique de Coree',
'MD' => 'Republique de Moldova',
'DO' => 'Republique Dominicaine',
'IR' => 'Republique Islamique d\' Iran',
'KP' => 'Republique Populaire Democratique de Coree',
'CZ' => 'Republique Tcheque',
'RE' => 'Reunion',
'RO' => 'Roumanie',
'GB' => 'Royaume-Uni',
'RW' => 'Rwanda',
'SN' => 'Senegal',
'EH' => 'Sahara Occidental',
'BL' => 'Saint-Barthelemy',
'KN' => 'Saint-Kitts-et-Nevis',
'SM' => 'Saint-Marin',
'MF' => 'Saint-Martin',
'PM' => 'Saint-Pierre-et-Miquelon',
'VA' => 'Saint-Siege (etat de la Cite du Vatican)',
'VC' => 'Saint-Vincent-et-les Grenadines',
'SH' => 'Sainte-Helene',
'LC' => 'Sainte-Lucie',
'WS' => 'Samoa',
'AS' => 'Samoa Americaines',
'ST' => 'Sao Tome-et-Principe',
'RS' => 'Serbie',
'SC' => 'Seychelles',
'SL' => 'Sierra Leone',
'SG' => 'Singapour',
'SI' => 'Slovenie',
'SK' => 'Slovaquie',
'SO' => 'Somalie',
'SD' => 'Soudan',
'LK' => 'Sri Lanka',
'SE' => 'Suede',
'CH' => 'Suisse',
'SR' => 'Suriname',
'SJ' => 'Svalbard et Île Jan Mayen',
'SZ' => 'Swaziland',
'TJ' => 'Tadjikistan',
'TD' => 'Tchad',
'TF' => 'Terres Australes Francaises',
'IO' => 'Territoire Britannique de lOcean Indien',
'PS' => 'Territoire Palestinien occupe',
'TH' => 'Thailande',
'TL' => 'Timor-Leste',
'TG' => 'Togo',
'TK' => 'Tokelau',
'TO' => 'Tonga',
'TT' => 'Trinite-et-Tobago',
'TN' => 'Tunisie',
'TM' => 'Turkmenistan',
'TR' => 'Turquie',
'TV' => 'Tuvalu',
'UA' => 'Ukraine',
'UY' => 'Uruguay',
'VU' => 'Vanuatu',
'VE' => 'Venezuela',
'VN' => 'Viet Nam',
'WF' => 'Wallis et Futuna',
'YE' => 'Yemen',
'ZM' => 'Zambie',
'ZW' => 'Zimbabwe'
);